[package]
name = "promkit"
version = "0.3.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2021"
description = "A toolkit for building your own interactive command-line tools"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[lib]
name = "promkit"
path = "src/lib.rs"

[dependencies]
crossterm = {version = "0.27.0", features = ["use-dev-tty"] }
radix_trie = "0.2.1"
scopeguard = "1.1.0"
serde = { version = "1.0.197" }
serde_json = "1.0.114"
thiserror = "1.0.50"
unicode-width = "0.1.8"

[dev-dependencies]
strip-ansi-escapes = "0.2.0"
