[package]
name = "promkit"
version = "0.1.2"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2018"
description = "A toolkit for building your own interactive command-line tools"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[lib]
name = "promkit"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.75"
crossterm = "0.27.0"
radix_trie = "0.2.1"
scopeguard = "1.1.0"
unicode-width = "0.1.8"

[dev-dependencies]
strip-ansi-escapes = "0.2.0"

[[example]]
name = "readline"
path = "examples/readline/readline.rs"
